# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'HTTP'), ('1', 'HTTPS'), ('2', 'Both')], max_length=1, verbose_name='type')),
                ('address', models.CharField(max_length=15, verbose_name='address')),
                ('speed', models.PositiveSmallIntegerField(verbose_name='speed')),
                ('stability', models.PositiveSmallIntegerField(verbose_name='stability')),
                ('rating', models.PositiveSmallIntegerField(editable=False, verbose_name='rating')),
            ],
            options={
                'ordering': ('-rating',),
            },
        ),
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
