# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_squashed_0004_auto_20170821_1857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAgent',
        ),
    ]
