# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_auto_20170821_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='address',
            field=models.CharField(max_length=30, unique=True, verbose_name='address'),
        ),
    ]
