# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 20:05
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parsers', '0002_auto_20170820_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Owner Ad'), ('1', 'Renter Ad')], default='0', max_length=1, verbose_name='type')),
                ('created', models.DateTimeField(blank=True, null=True, verbose_name='date created')),
                ('received', models.DateTimeField(auto_now_add=True, verbose_name='date received')),
                ('raw', models.BooleanField(default=True, verbose_name='raw')),
                ('url', models.URLField(blank=True, default='', verbose_name='url')),
                ('description', models.TextField(blank=True, default='', max_length=1024, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='name')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
                ('vk', models.URLField(blank=True, default='', verbose_name='vkontakte url')),
                ('fb', models.URLField(blank=True, default='', verbose_name='facebook url')),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Flat'), ('1', 'Room'), ('2', 'Bed')], default='0', max_length=1, verbose_name='type')),
                ('area', models.FloatField(blank=True, null=True, verbose_name='area')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='cost')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rooms')),
            ],
            options={
                'verbose_name': 'Flat',
                'verbose_name_plural': 'Flats',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Local image'), ('1', 'Remote image')], default='0', max_length=1, verbose_name='type')),
                ('url', models.URLField(blank=True, default='', verbose_name='remote url')),
                ('image', models.ImageField(upload_to='images/', verbose_name='local image')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.Ad')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='name')),
                ('location', annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
            ],
            options={
                'verbose_name': 'Metro',
                'verbose_name_plural': 'Metros',
            },
        ),
        migrations.AddField(
            model_name='flat',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AddField(
            model_name='flat',
            name='metros',
            field=models.ManyToManyField(blank=True, related_name='flats', to='core.Metro'),
        ),
        migrations.AddField(
            model_name='ad',
            name='contacts',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='core.Contacts'),
        ),
        migrations.AddField(
            model_name='ad',
            name='flat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad', to='core.Flat'),
        ),
        migrations.AddField(
            model_name='ad',
            name='parser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='parsers.Parser'),
        ),
    ]
