# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170821_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='parser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='parsers.Parser'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='local image'),
        ),
    ]
