# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170824_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='raw',
        ),
        migrations.AddField(
            model_name='ad',
            name='complete',
            field=models.BooleanField(default=True, verbose_name='complete'),
        ),
    ]
