# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170824_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metro',
            options={'ordering': ('name',), 'verbose_name': 'Metro', 'verbose_name_plural': 'Metros'},
        ),
    ]
