# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170824_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='type',
            field=models.CharField(choices=[('0', 'Квартира'), ('1', 'Комната'), ('2', 'Кровать')], default='0', max_length=1, verbose_name='type'),
        ),
    ]
