# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='parser',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='location',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='metros',
        ),
        migrations.RemoveField(
            model_name='image',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='metro',
            name='location',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Flat',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Metro',
        ),
    ]
