# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 18:36
from __future__ import unicode_literals

import accounts.models
import annoying.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('role', models.CharField(choices=[('0', 'Владелец'), ('1', 'Арендатор')], default='0', max_length=10, verbose_name='role')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='name')),
                ('second_name', models.CharField(default=None, max_length=128, verbose_name='second_name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('vn_action', models.CharField(blank=True, choices=[('0', 'NONE'), ('1', 'REG'), ('2', 'PASS')], max_length=10, verbose_name='verification action')),
                ('vn_key', models.CharField(blank=True, max_length=50, verbose_name='verification key')),
                ('vn_expire', models.DateTimeField(blank=True, default=None, null=True, verbose_name='verification key expire')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, verbose_name='phone')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Юзеры',
                'verbose_name': 'Юзер',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.CharField(blank=True, default=None, max_length=128, null=True, validators=[django.core.validators.URLValidator()])),
                ('fb', models.CharField(blank=True, default=None, max_length=128, null=True, validators=[django.core.validators.URLValidator()])),
                ('tw', models.CharField(blank=True, default=None, max_length=128, null=True, validators=[django.core.validators.URLValidator()])),
                ('go', models.CharField(blank=True, default=None, max_length=128, null=True, validators=[django.core.validators.URLValidator()])),
                ('user', annoying.fields.AutoOneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cоцcети юзеров',
                'verbose_name': 'Cоцcети юзера',
            },
        ),
    ]
