# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 17:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.CharField(blank=True, default=None, max_length=128, null=True, validators=[django.core.validators.URLValidator()])),
                ('fb', models.CharField(blank=True, default=None, max_length=128, null=True, validators=[django.core.validators.URLValidator()])),
                ('tw', models.CharField(blank=True, default=None, max_length=128, null=True, validators=[django.core.validators.URLValidator()])),
                ('go', models.CharField(blank=True, default=None, max_length=128, null=True, validators=[django.core.validators.URLValidator()])),
            ],
            options={
                'verbose_name': 'Cоцcети юзера',
                'verbose_name_plural': 'Cоцcети юзеров',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Юзер', 'verbose_name_plural': 'Юзеры'},
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'Owner'), ('1', 'Renter')], default='0', max_length=10, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.CharField(default=None, max_length=128, verbose_name='second_name'),
        ),
        migrations.AddField(
            model_name='socialnetworks',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to=settings.AUTH_USER_MODEL),
        ),
    ]
