# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-01 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170801_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='second_name'),
        ),
    ]
