# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 20:11
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170801_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworks',
            name='user',
            field=annoying.fields.AutoOneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('0', 'Владелец'), ('1', 'Арендатор')], default='0', max_length=10, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_name',
            field=models.CharField(default=None, max_length=128, verbose_name='second_name'),
        ),
    ]
