# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170805_0005'),
        ('accounts', '0005_auto_20170804_2322'),
    ]

    operations = [
    ]
