# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170804_2322'),
        ('accounts', '0004_auto_20170805_0005'),
    ]

    operations = [
    ]
