# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20170805_0016'),
        ('accounts', '0006_merge_20170805_0940'),
    ]

    operations = [
    ]
